/** @type {import("prettier").Config} */
export default {
  printWidth: 80,
  trailingComma: "es5",
  tabWidth: 2,
  semi: true,
  singleQuote: false,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "always",
  singleAttributePerLine: true,
  jsxSingleQuote: false,
  plugins: [
    "@trivago/prettier-plugin-sort-imports",
    "prettier-plugin-packagejson",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrder: [
    "^react$",
    "^react-dom$",
    "^next(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^@/config/(.*)$",
    "^@/lib/(.*)$",
    "^@/hooks/(.*)$",
    "^@/components/(.*)$",
    "^@/layouts/(.*)$",
    "^@/styles/(.*)$",
    "^@/utils/(.*)$",
    "^@/types/(.*)$",
    "^[./]",
  ],
};
